server:
  port: 8072

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true
jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
